# Generated by Django 4.2.8 on 2024-01-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vriho_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPulses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('product_price_1kg', models.FloatField(blank=True)),
                ('product_photo', models.ImageField(blank=True, upload_to='pulse_uploads/')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('benefits', models.CharField(blank=True, max_length=500)),
                ('availability', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('product_price_1kg', models.FloatField(blank=True)),
                ('product_photo', models.ImageField(blank=True, upload_to='rice_uploads/')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('benefits', models.CharField(blank=True, max_length=500)),
                ('cooking_method', models.ImageField(blank=True, upload_to='rice_uploads/')),
                ('availability', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VrihodhaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, upload_to='vrihodha_uploads/')),
                ('company_number', models.BigIntegerField(blank=True, null=True)),
                ('company_address', models.JSONField(blank=True, null=True)),
                ('terms_and_conditions', models.FileField(blank=True, upload_to='vrihodha_uploads/')),
                ('privacy_policy', models.CharField(max_length=500)),
                ('about_us', models.CharField(max_length=500)),
            ],
        ),
    ]
