# Generated by Django 4.2.8 on 2024-01-03 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vriho_app', '0004_userfeedback_orderdetails_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
